### PR TITLE
Fix compatibility with Rails edge

### PR DESCRIPTION
**Pull request by casperisfine**
https://github.com/rails/rails/commit/52f0b050e25cac6d9571d71c9f74ea583d8aa2b0#diff-4c1f3e49dbd40e9f860377cac33e1a0e got rid of the `sanitizer_vendor` API.

cc @rafaelfranca @Edouard-Chin

### CODE REVIEW

**Comment by rafaelfranca** [comment]
We still need the `safe_list_sanitizer` here.

**Comment by rafaelfranca** [comment]
@casperisfine can you update the PR to just define a `safe_list_sanitizer`

**Comment by casperisfine** [comment]
I updated the PR to simply add `safe_list_sanitizer`.

**Comment by pschambacher** [comment]
👋 Any plan to release a v1.0.4 of the gem with this PR in it?

**Comment by codealchemy** [comment]
> 👋 @rafaelfranca Any plan to release a v1.0.4 of the gem with this PR in it?

Curious about this as well, it seems (aside from doc updates) [these are the only changes since the last release](https://github.com/rails/rails-deprecated_sanitizer/compare/v1.0.3...master), but Rails 6 applications can't use this gem.

**Pull request merged**
